### ISSUE TITLE
Installation and Setup

### ISSUE THREAD

**Issue by zeeshanjan82** [btroncone/ngrx-examples#13]
While trying to install the ShoppingCart application on my local env. I tried running npm install however I am using windows and am getting errors like : Cannot find name 'require', Cannot find name 'Promise' I have also tried to run the command:typings install but still getting the same error.

**Comment by tja4472** [comment]
Hi

Try adding
```
    "typings": "0.8.1",
```

to package.json.

Then delete typings folder and redo 
```
npm install
```

You probably have typings 1.x installed globally.

**Comment by zeeshanjan82** [comment]
thanks @tja4472 the issue is resolved now.
