### ISSUE TITLE
Example App: Echoes Player (open source)

### ISSUE THREAD

**Issue by orizens** [btroncone/ngrx-examples#24]
hi @btroncone 
I developed Echoes Player with ngrx/store, ngrx/effects - following nice conventions using observables strategy. I think it's a good fit for the code samples section. 
repo: http://github.com/orizens/echoes-ng2 
production app: http://beta.echotu.be (or http://orizens.github.io/echoes-ng2)

Thanks.

**Comment by btroncone** [comment]
I'm so sorry, I have not been keeping up with this repo like I should and missed this request. Really awesome work! 👍

**Comment by orizens** [comment]
thank you!
